version: '3'
services:
  frontend:
    build:
      context: ./client-app/contact-manager-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server-app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
