version: '3.8'

services:
  frontend:
    build:
      context: ./client-app/contact-manager-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server-app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  mongo-data:
